=== Global19-atlassian-net/iottestware.fuzzing/resources/schema/root.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "title": "Root Schema",
  "description": "The root schema defines the configuration of the fuzzer",
  "type": "object",
  "required": [ "protocolModule", "generators", "mutators", "filters", "rules" ],

  "properties": {
    "protocolModule": { "$ref": "protocols.json#/definitions/protocolModule" },
    "generators": { "$ref": "generators.json#/definitions/generators" },
    "mutators": { "$ref": "mutators.json#/definitions/mutatorList" },
    "filters": { "$ref": "filters.json#/definitions/filterList" },
    "rules": { "$ref": "rules.json#/definitions/rules" }
  }
}

=== Global19-atlassian-net/iottestware.fuzzing/resources/samples/mqtt_client_01.json
{
  "protocolModule": {
    "protocol": "MQTT",
    "encoding": "utf-8",
    "payload": "json"
  },


  "generators": [
    { "id": "g_rand_uniform" } ],


  "mutators": [
    { "id": "m_xor_payload", "field": "value.field_name", "binary": "XOR", "generator": "g_rand_uniform" },
    { "id": "m_rnd_retcode", "field": "retcode", "binary": "SET", "generator": "g_rand_uniform" },
    { "id": "m_rnd_type", "field": "type", "binary": "SET", "generator": "g_rand_uniform" },
    { "id": "m_rnd_rem_len", "field": "len", "binary": "SET", "generator": "g_rand_uniform" },
    { "id": "m_incr_type", "field": "type", "unary": "INCR" },
    { "id": "m_rnd_qos", "field": "QOS", "binary": "SET", "generator": "g_rand_uniform" },
    { "id": "m_invert_flags_dup", "field": "DUP", "unary": "NOT" },
    { "id": "m_incr_flags_qos", "field": "QOS", "unary": "INCR" },
    { "id": "m_invert_flags_session", "field": "sessPresentFlag", "unary": "NOT" },
    { "id": "m_invert_flags_retain", "field": "RETAIN", "unary": "NOT" }
  ],


  "filters": [
    {
      "id": "f_connack",
      "description": "This filter matches all CONNACK packets",
      "direction": "Response",
      "filter": { "field": "type", "op": "-eq", "value": 2 }
    }, {
      "id": "f_puback",
      "description": "Complex filter matches ACK message in Publish sequence with QoS > 0",
      "direction": "Response",
      "left": {
        "left": { "filter": { "field": "type", "op": "-eq", "value": 4 } },
        "op": "OR",
        "right": { "filter": { "field": "type", "op": "-eq", "value": 5 } } },
      "op": "OR",
      "right": { "filter": { "field": "type", "op": "-eq", "value": 6 } }
    }, {
      "id": "f_publish_qos_2",
      "description": "Matches publish packets and all packets having QoS == 2",
      "direction": "Response",
      "left": { "filter": { "field": "type", "op": "-eq", "value": 3 } },
      "op": "AND",
      "right": { "filter": { "field": "QOS", "op": "-eq", "value": 2 } }
    } ],


  "rules": [
    {
      "match": "f_connack",
      "distribution": {
        "model": "multinomial",
        "items": [
          { "strength": 15, "mutators": [ ] },
          { "strength": 15, "mutators": [ "m_rnd_type", "m_rnd_rem_len" ] },
          { "strength": 10, "mutators": [ "m_rnd_retcode" ] },
          { "strength": 10, "mutators": [ "m_rnd_retcode", "m_rnd_type" ] },
          { "strength": 10, "mutators": [ "m_rnd_retcode", "m_rnd_type", "m_invert_flags_session", "m_invert_flags_dup", "m_invert_flags_retain" ] },
          { "strength": 5, "mutators": [ "m_incr_flags_qos", "m_invert_flags_dup", "m_invert_flags_session" ] }
        ] }
    }, {
      "match": "f_puback",
      "mutators": [ "m_incr_type", "m_invert_flags_dup", "m_rnd_rem_len" ]
    }, {
      "match": "f_publish_qos_2",
      "mutators": [ "m_invert_flags_dup", "m_xor_payload" ]
    } ]
}

=== Global19-atlassian-net/iottestware.fuzzing/resources/samples/mqtt_02.json
{
  "protocolModule": {
    "protocol": "MQTT",
    "encoding": "utf-8",
    "payload": "json"
  },


  "generators": [ { "id": "g_rand_uniform" } ],


  "mutators": [
    { "id": "m_xor_protoname_fixed", "field": "protoname", "binary": "XOR", "hex": "0xA5A5" },
    { "id": "m_inc_protolevel", "field": "protolevel", "unary": "INCR" },
    { "id": "m_inc_clientid_len", "field": "clientIdlen", "unary": "INCR" },
    { "id": "m_replace_clientid", "field": "clientId",  "binary": "SET", "generator": "g_rand_uniform" },
    { "id": "m_replace_username", "field": "username",  "binary": "SET", "generator": "g_rand_uniform" },
    { "id": "m_invert_username_flag", "field": "usernameflag", "unary": "NOT" },
    { "id": "m_invert_flags_dup", "field": "DUP", "unary": "NOT" },
    { "id": "m_invert_flags_retain", "field": "RETAIN", "unary": "NOT" },
    { "id": "m_invert_flags_qos", "field": "QOS", "unary": "NOT" },
    { "id": "m_inc_flags_qos", "field": "QOS", "unary": "INCR" },
    { "id": "m_inc_pl_length", "field": "length", "unary": "INCR" },
    { "id": "m_inc_rem_length", "field": "len", "unary": "INCR" },
    { "id": "m_dec_rem_length", "field": "len", "unary": "DECR" },
    { "id": "m_xor_topic", "field": "topic", "binary": "XOR", "hex": "0xFF551177" },
    { "id": "m_xor_topic_2", "field": "topic", "binary": "XOR", "hex": "0xFF551177" },
    { "id": "m_or_topic", "field": "topic", "binary": "XOR", "generator": "g_rand_uniform" },
    { "id": "m_set_pl_length", "field": "length", "binary": "SET", "generator": "g_rand_uniform" }
  ],


  "filters": [
    {
      "id": "f_all_connect",
      "description": "This filter matches all connect packets",
      "direction": "Request",
      "filter": { "field": "type", "op": "-eq", "value": 1 }
    }, {
      "id": "f_publish_subscribe",
      "descritpion": "Matches all publish or subscribe or unsubscribe packets",
      "direction": "All",
      "left": {
        "left": { "filter": { "field": "type", "op": "-eq", "value": 3 } },
        "op": "OR",
        "right": { "filter": { "field": "type", "op": "-eq", "value": 8 } } },
      "op": "OR",
      "right": { "filter": { "field": "type", "op": "-eq", "value": 10 } }
    } ],


  "rules": [
    {
      "match": "f_all_connect",
      "distribution": {
        "model": "multinomial",
        "items": [
          { "strength": 1, "mutators": [ "m_xor_protoname_fixed", "m_inc_protolevel" ] },
          { "strength": 2, "mutators": [ "m_replace_username", "m_invert_username_flag" ] },
          { "strength": 3, "mutators": [ "m_replace_clientid", "m_invert_username_flag" ] },
          { "strength": 4, "mutators": [ "m_inc_clientid_len" ] },
          { "strength": 4, "mutators": [ "m_replace_clientid" ] },
          { "strength": 4, "mutators": [ "m_inc_clientid_len", "m_replace_clientid" ] },
          { "strength": 5, "mutators": [ "m_invert_flags_dup", "m_invert_flags_qos" ] },
          { "strength": 45, "mutators": [ ] }
        ] }
    }, {
      "match": "f_publish_subscribe",
      "distribution": {
        "model": "multinomial",
        "items": [
          { "strength": 7, "mutators": [ "m_invert_flags_retain", "m_inc_flags_qos", "m_or_topic" ] },
          { "strength": 7, "mutators": [ "m_invert_flags_retain", "m_xor_topic" ] },
          { "strength": 9, "mutators": [ "m_invert_flags_retain", "m_inc_flags_qos", "m_or_topic", "m_set_pl_length" ] },
          { "strength": 10, "mutators": [ "m_invert_flags_retain", "m_xor_topic", "m_inc_pl_length" ] },
          { "strength": 10, "mutators": [ "m_inc_pl_length" ] },
          { "strength": 15, "mutators": [ "m_inc_pl_length", "m_xor_topic_2" ] },
          { "strength": 12, "mutators": [ "m_set_pl_length" ] },
          { "strength": 10, "mutators": [ "m_inc_rem_length" ] },
          { "strength": 2, "mutators": [ "m_dec_rem_length" ] },
          { "strength": 10, "mutators": [ "m_dec_rem_length", "m_invert_flags_retain" ] },
          { "strength": 10, "mutators": [ "m_inc_rem_length", "m_invert_flags_retain" ] },
          { "strength": 15, "mutators": [ ] }
        ] }
    } ]
}

=== Global19-atlassian-net/iottestware.fuzzing/resources/samples/mqtt_01.json
{
  "protocolModule": {
    "protocol": "MQTT",
    "encoding": "utf-8",
    "payload": "json"
  },


  "generators": [
    { "id": "g_rand_uniform" },
    { "id": "g_rand_uniform_2" },
    { "id": "g_with_seed", "seed": 123 } ],


  "mutators": [
    { "id": "m_xor_protoname_fixed", "field": "protoname", "binary": "XOR", "hex": "0xA5A5" },
    { "id": "m_inc_protolevel", "field": "protolevel", "unary": "INCR" },
    { "id": "m_inc_clientid_len", "field": "clientIdlen", "unary": "INCR" },
    { "id": "m_xor_payload", "field": "value.field_name", "binary": "XOR", "generator": "g_rand_uniform" },
    { "id": "m_replace_clientid", "field": "clientId",  "binary": "SET", "generator": "g_with_seed" },
    { "id": "m_replace_username", "field": "username",  "binary": "SET", "generator": "g_rand_uniform_2" },
    { "id": "m_invert_username_flag", "field": "usernameflag", "unary": "NOT" },
    { "id": "m_invert_flags_dup", "field": "DUP", "unary": "NOT" },
    { "id": "m_invert_flags_qos", "field": "QOS", "unary": "NOT" }
  ],


  "filters": [
    {
      "id": "f_all_connect",
      "description": "This filter matches all connect packets",
      "direction": "Request",
      "filter": { "field": "type", "op": "-eq", "value": 1 }
    }, {
      "id": "f_publish_qos_lt2_or_subscribe",
      "description": "Complex filter matches conditionally publish or subscribe packets",
      "direction": "Request",
      "left": {
        "left": { "filter": { "field": "type", "op": "-eq", "value": 3 } },
        "op": "AND",
        "right": { "filter": { "field": "QOS", "op": "-lt", "value": 2 } } },
      "op": "OR",
      "right": { "filter": { "field": "type", "op": "-eq", "value": 8 } }
    }, {
      "id": "f_publish_qos_2",
      "description": "Matches publish packets and all packets having QoS == 2",
      "direction": "Request",
      "left": { "filter": { "field": "type", "op": "-eq", "value": 3 } },
      "op": "AND",
      "right": { "filter": { "field": "QOS", "op": "-eq", "value": 2 } }
    } ],


  "rules": [
    {
      "match": "f_all_connect",
      "distribution": {
        "model": "multinomial",
        "seed": 3456,
        "nxp": 10,
        "items": [
          { "strength": 1, "mutators": [ "m_xor_protoname_fixed", "m_inc_protolevel" ] },
          { "strength": 12, "mutators": [ "m_replace_username", "m_invert_username_flag" ] },
          { "strength": 15, "mutators": [ "m_inc_clientid_len", "m_replace_clientid" ] },
          { "strength": 7, "mutators": [ "m_invert_flags_dup", "m_invert_flags_qos" ] },
          { "strength": 15, "mutators": [ ] }
        ] }
    }, {
      "match": "f_publish_qos_lt2_or_subscribe",
      "mutators": [ "m_invert_flags_qos" ]
    }, {
      "match": "f_publish_qos_2",
      "mutators": [ "m_invert_flags_dup", "m_xor_payload" ]
    } ]
}

=== Global19-atlassian-net/iottestware.fuzzing/resources/samples/coap_02.json
{
  "protocolModule": {
    "protocol": "CoAP",
    "encoding": "utf-8",
    "payload": "raw"
  },

  "generators": [
    { "id": "g_rand_uniform" },
    { "id": "g_with_seed", "seed": 123 } ],

  "mutators": [
    { "id": "m_not_code_0", "field": "code", "unary": "NOT" },
    { "id": "m_incr_code0", "field": "code", "unary": "INCR" },
    { "id": "m_xor_code_1", "field": "code", "binary": "XOR", "hex": "0xA5A5" },
    { "id": "m_xor_code_2", "field": "code", "binary": "AND", "generator": "g_rand_uniform" }
  ],

  "filters": [
    {
      "id": "f_type_rst",
      "description": "This filter matches all RST messages (CoAP.type == 3)",
      "direction": "Request",
      "filter": { "field": "type", "op": "-eq", "value": 3 }
    } ],

  "rules": [
    {
      "match": "f_type_rst",
      "mutators": [ "m_xor_code_1" ]
    } ]
}
